### ISSUE TITLE
Getting error while performing "Create and import default component, on the fly"

### ISSUE THREAD

**Issue by suvel-the-dev** [razgraf/react-on-the-fly#1]
Hi, I was exploring the VS code extensions and came by this one. Always wanted to do something abt making the process of creating components easy, never would have thought an extension could do that. **Thanks for creating one🤝.**

Regarding the issue, I just installed "React on the fly", wrote and selected the component name, then chose "Create and import default component, on the fly". Then this error popped up **"VeryNewComponent" directory. Check if a directory with the same name is not already there. [react-on-the-fly]**.

![image](https://user-images.githubusercontent.com/84700466/124081257-f06c1080-da68-11eb-8c36-4946f889b9fa.png)

**Comment by razgraf** [comment]
Hi @suvel-the-dev ! Thanks a lot for testing out the extension, really happy that you gave it a shot and that it may help your development process.

I'm not exactly sure what happened there, so let's see if we can diagnose the problem together. Normally, after you select the component name and hit "create.." it would drop a folder with that name in the same path as the file you're currently in.

- First, I would refresh the file tree in VSCode to see if the folder is not already there in `src/VeryNewComponent`
- Second thing I would try is create the on-the-fly component through an alternative method: go to the file tree, right click on a folder and search for one of the on-the-fly commands in the menu. It should prompt you to input the name of the component. Make sure to click on a folder, as clicking on a file won't work (for now).

I'm trying to reproduce the error on my setup, so any other debugging details are more than welcomed!

Question: What is your setup, as in Mac/Windows/Linux?
Later update: It may have to do with my use of the `fs` and `path` utilities, will investigate.

**Comment by razgraf** [comment]
I've figured out the issue, and redeployed (tested on windows as well as mac). It should fix the issue, where the active path had been cut by `vscode.Uri.parse()`. I've transitioned to `vscode.Uri.file()` which seems to keep the integrity of the path on Windows as well ([docs](https://code.visualstudio.com/api/references/vscode-api#Uri)).

Thank you for the feedback @suvel-the-dev , lmk if it works now :)

**Comment by suvel-the-dev** [comment]
@razgraf it is working now. Thank you for fixing it.

BTW, is there a way to configure where to create and what files need to be created? Because I always put my component inside the component folder and have an index.js and style.css

**Comment by razgraf** [comment]
@suvel-the-dev That's a really good idea to be included in a v2. Right now the create & import follows either the file you are in or, in case of the simple create, the folder you right click on. It also only creates an `index.js` at the moment. 

I'll think of a configuration file where you can define multiple templates (for more files at a time) and file locations, when I get to the v2. Thanks for the feedback!
